### ISSUE TITLE
Add steam, dropbox, blender

### ISSUE THREAD

**Issue by DraGiuS** [mdrights/LiveSlak#3]

**Comment by mdrights** [comment]
Well, as LiveSlak's primary purpose is on tackling privacy and security issues, apps other than dealing with digital privacy will be considered later....

Also, see if anyone else supports your idea :)

**Comment by meaaiiaa** [comment]
in favour of adding linux kernel compilation enhancement, right now some wireless network driver should be started with compiling the kernel, it happens that this LIVE OS doesn't have such capability. Thanks a lot.

**Comment by mdrights** [comment]
@meaaiiaa You had asked this question on another issue (post) and I answered. So close this issue :)

PS. You make your self-recompiled kernel, add it to the repo which Liveslak will be built from. And then build your own Liveslak.
