### ISSUE TITLE
基于liveslak的iso制作的系统遇到的问题

### ISSUE THREAD

**Issue by meaaiiaa** [mdrights/LiveSlak#4]
你好，mdrights,

在网上找了很久这样的系统，终于有一款能大致体适合自己。可是偏偏我的笔记本是BROADCOM的无线网卡，那个网卡驱动比较奇葩，在4.19.13的内核下还要重新编译下驱动模块，结果一直编译有错误。看了CENTOS的介绍，说是还要修改很多地方结合内核文件才能编译通过。

但是我之前使用alien的那一版旧内核的版本是没有问题的，请问你有好的建议吗？

**Comment by mdrights** [comment]
你好，meaaiiaa，

这样的话，你可以尝试自己打包构建 Liveslak，构建时你就可以采用你自己重新编译过（和/或 添加过特定驱动的）的内核了。

我现在 Liveslak 2019.01 的内核也是自己重新编译过的。我可以写个关于如何构建这个发行版的文档供参考。
我这还有个内核编译脚本，望有点帮助：https://github.com/slackwarecn-slackbuilds/kernel-self-build

ps. 编译驱动模块时留意厂商指定该驱动所适用的内核版本范围，不然肯定编译不过。

**Comment by mdrights** [comment]
构建文档加上来了：https://github.com/mdrights/LiveSlak#build
